name: NPM Audit Badge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      id: audit
      run: |
        # Run npm audit and capture the output
        OUTPUT=$(npm audit --json || true)

        # Extract vulnerability counts
        TOTAL=$(echo $OUTPUT | jq '.metadata.vulnerabilities.total' 2>/dev/null || echo "0")
        INFO=$(echo $OUTPUT | jq '.metadata.vulnerabilities.info' 2>/dev/null || echo "0")
        LOW=$(echo $OUTPUT | jq '.metadata.vulnerabilities.low' 2>/dev/null || echo "0")
        MODERATE=$(echo $OUTPUT | jq '.metadata.vulnerabilities.moderate' 2>/dev/null || echo "0")
        HIGH=$(echo $OUTPUT | jq '.metadata.vulnerabilities.high' 2>/dev/null || echo "0")
        CRITICAL=$(echo $OUTPUT | jq '.metadata.vulnerabilities.critical' 2>/dev/null || echo "0")

        # Determine badge color based on vulnerability count
        if [ "$TOTAL" -eq "0" ]; then
          COLOR="brightgreen"
          STATUS="passing"
        else
          COLOR="red"
          STATUS="failing"
        fi

        # Create badge data
        echo "total=$TOTAL" >> $GITHUB_OUTPUT
        echo "info=$INFO" >> $GITHUB_OUTPUT
        echo "low=$LOW" >> $GITHUB_OUTPUT
        echo "moderate=$MODERATE" >> $GITHUB_OUTPUT
        echo "high=$HIGH" >> $GITHUB_OUTPUT
        echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
        echo "color=$COLOR" >> $GITHUB_OUTPUT
        echo "status=$STATUS" >> $GITHUB_OUTPUT

    - name: Create workflow summary
      run: |
        echo "## NPM Audit Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Status | Vulnerabilities |" >> $GITHUB_STEP_SUMMARY
        echo "| ------ | --------------- |" >> $GITHUB_STEP_SUMMARY
        echo "| Status | ${{ steps.audit.outputs.status }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Total | ${{ steps.audit.outputs.total }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Info | ${{ steps.audit.outputs.info }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Low | ${{ steps.audit.outputs.low }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Moderate | ${{ steps.audit.outputs.moderate }} |" >> $GITHUB_STEP_SUMMARY
        echo "| High | ${{ steps.audit.outputs.high }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Critical | ${{ steps.audit.outputs.critical }} |" >> $GITHUB_STEP_SUMMARY
